unique_ids:
  forms: {Front: EJCZQWGXVD4DTCMYGQUILHFMJFLLHQTJ, Front.Browse: C6WDXNIBMJ7NUUQUM5YDARUF7FI66YNE,
    Front.Browse.RowTemplate2: WO2KH5BNXGZ2RMLFEONTWJHKJ3DVCQBH, Front.Browse.RowTemplate3: 7HKMH4BF3I57ZFNYRVXSV36UT344VVSG,
    Front.RowTemplate1: N32ZYRZVJK465Z5HPGDKV4URPWRIFABC, Front.RowTemplate4: JQ3XLZI23BVZ33DICI3ZHJR3AEH4AXYO,
    Front_copy: JJQO5DRBQ6M3QYFAQRYNGZ23PGQSYWZE}
  modules: {Function: 4MVACNS7464JNMI5624UNRGKENO7DBFO}
  server_modules: {ServerModule1: IYR4N3CWJYQE36BPRDICGVT73Q7VXRUL}
  assets: {standard-page.html: QZTJZVJGHD5JF5RURYA652GT2FF462U6, theme.css: A7KCIDZULURXG7YLQU6YCRKTP7RZDLHR}
